#ifndef COMMAND_DISPATCH_RULES_H
#define COMMAND_DISPATCH_RULES_H

enum CommandDispatchKind
{
  COMMAND_DISPATCH_INVALID,
  COMMAND_DISPATCH_G0,
  COMMAND_DISPATCH_G1,
  COMMAND_DISPATCH_G28,
  COMMAND_DISPATCH_G92,
  COMMAND_DISPATCH_M201,
  COMMAND_DISPATCH_M203,
  COMMAND_DISPATCH_M503,
  COMMAND_DISPATCH_SYNC,
  COMMAND_DISPATCH_BEGIN,
  COMMAND_DISPATCH_END,
};

CommandDispatchKind classifyCommandToken(const char* command);

#endif