[platformio]
default_envs = megaatmega2560
src_dir = .

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_flags =
  -I.
  -Icommands
build_src_filter =
  +<BigRobotArm.ino>
  +<*.cpp>
  +<commands/*.cpp>
  -<BigRobotArm/>
lib_deps =
  waspinator/AccelStepper@^1.64
  arduino-libraries/Servo@^1.2.2